const quotesObject = {
    "quotes":
    [
       { "quote":"Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.", "author":"Dalai Lama"},
       {"quote":"Why fit in when you were born to stand out?", "author":"Dr.Seuss"},
       {"quote":"Aging is an extraordinary process where you become the person you always should have been.", "author":"David Bowie"},
       {"quote":"The two most important days in your life are the day you were born and the day you find out why.", "author":"Mark Twain"},
       {"quote":"Let's begin by taking a smallish nap or two.", "author":"Winnie the Pooh/AA Milne"},
       {"quote":"The price of anything is the amount of life you exchange for it.", "author":"Henry David Thoreau"},
       {"quote":"Out beyond ideas of wrongdoing and rightdoing there is a field. I'll meet you there.", "author":"Rumi"},
       {"quote":"Leer buenos libros es como conversar con las mejores mentels del pasado.", "author":"Rene Descartes"},
       {"quote":"I still find each day too short for all the thoughts I want to think, all the walks I want to take, all the books I want to read, and all the friends I want to see.", "author":"John Burroughs"},
       {"quote":"Thinking 'here goes nothing' could be the start of everything.", "author":"Drew Wagner"},
       {"quote":"Take a lover who looks at you like maybe you are magic.", "author":"Frida Kahlo"},
       {"quote":"Do not worry that your life is turning upside down. How do you know that the side you are used to is better than the one to come?", "author":"Rumi"},
       {"quote":"I am always doing that which I cannot do, in order that I may learn how to do it.", "author":"Pablo Picasso"},
       {"quote":"Experience: that most brutal of teachers. But you learn, my God do you learn.", "author":"C.S. Lewis"},
       {"quote":"Be grateful for who ever comes, because each has been sent as a guide from beyond.", "author":"Rumi"},
       {"quote":"See the light in others and treat them as if that is all you see.", "author":"Dr. Wayne Dyer"},
       {"quote":"You are the universe in ecstatic motion.", "author":"Rumi"},
       {"quote":"Take your pleasure seriously.", "author":"Charles Eames"},
       {"quote":"One of the advantages of being disorganized is that one is always having surprise discoveries.", "author":"Winnie the Pooh/AA Milne"},
       {"quote":"It's better to look back on life and say: 'I can't believe I did that.' than to look back and say: 'I wish I did that.", "author":"Unknown"},
       {"quote":"Nothing is permanent in this wicked world, not even our troubles.", "author":"Charlie Chaplin"},
       {"quote":"I've loved the stars too fondly to be fearful of the night.", "author":"Galileo"},
       {"quote":"Pour yourself a drink, put on some lipstick, and pull yourself together.", "author":"Liz Taylor"},
       {"quote":"You are you. This is truer than true. There is no one alive who is youer than you.", "author":"Dr. Seuss"},
       {"quote":"La lectura es el viaje de los que no pueden tomar el tren.", "author":"F. Croisset"},
       {"quote":"If you want your children to be intelligent, read them fairy tales.", "author":"Einstein"},
       {"quote":"You are going to want to give up. Don't.", "author":"Unknown"},
       {"quote":"Listen to the mustn'ts child, listen to the don'ts. Listen to the shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then listen close to me- anything can happen, child. Anything can be.", "author":"Shel Silverstein"},
       {"quote":"Whatever you are, be a good one.", "author":"Abraham Lincoln"},
       {"quote":"I think it's very healthy to spend time alone. You need to know how to be alone and not be defined by another person.", "author":"Oscar Wilde"},
       {"quote":"Imagine meeting someone who understood even the dustiest corners of your mixed-up soul.", "author":"Unknown"},
       {"quote":"Not all those who wander are lost.", "author":"J.R.R Tolkien"},
       {"quote":"We're all a little weird, and life's a little weird. And when we find someone whose weirdness is compatible with ours, we join up with them and fall in mutual weirdness and call it love.", "author":"Dr. Seuss"},
       {"quote":"Lo que no me mata me alimenta.", "author":"Friedrich Nietzsche"},
       {"quote":"I hope you live a life you're proud of. If you find that you are not, I hope you have the strength to start all over again.", "author":"F. Scott Fitzgerald"},
       {"quote":"A million dreams are keeping me awake.", "author":"Benj Pasek and Justin Paul"},
       {"quote":"She understood that the hardest times in life to go through were when you were transitioning from one version of yourself to another.", "author":"Sarah Addison Allen"},
       {"quote":"What if I fall? Oh, but my darling, what if you fly?", "author":"Erin Hanson"},
       {"quote":"My coach said I ran like a girl, and I said if he ran a little faster, he could too.", "author":"Mia Hamm"},
       {"quote":"You know all those things you've always wanted to do? You should go do them.", "author":"E.J. Lamprey"},
       {"quote":"She turned her can'ts into cans and her dreams into plans.", "author":"Kobi Yamada"},
       {"quote":"If we did all the things we are capable of doing, we would literally astonish ourselves.", "author":"Thomas Edison"}
    ]
};

export default quotesObject ;